name: CI ReUse - Build
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      dockerBuild:
        required: true
        type: string
      appName:
        required: true
        type: string
jobs:
  NodeJS_Build:
    if: inputs.appType == 'nodejs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: echo npm install

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Login to ACR
        run: az acr login --name roboshopacr
#      - name: Docker Build
#        if: inputs.dockerBuild == 'true'
#        env:
#          CLIENT_ID : ${{ secrets.CLIENT_ID }}
#          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#          TENANT_ID: ${{ vars.TENANT_ID }}
#        run: |
#          az login --service-principal  --username $CLIENT_ID --password $CLIENT_SECRET --tenant $TENANT_ID
#          az acr login --name roboshopacr
#          docker build -t roboshopacr.azureacr.io/roboshop-${{ inputs.appName }}:${{ github.sha }} .
  Maven_Build:
    if: inputs.appType == 'maven'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn package