name: CI ReUse - MAIN
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
jobs:
  Build:
    uses: vineethbandlamudi/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      dockerBuild: "false"
  Test:
    needs: Build
    uses: vineethbandlamudi/roboshop-github-actions/.github/workflows/test.yml@main
    with:
      appType: '${{ inputs.appType }}'
  DockerBuild:
    needs: Test
    uses: vineethbandlamudi/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      dockerBuild: "true"
  DEV:
    needs: Test
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dev Env"
  QA:
    needs: DEV
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - run: echo "QA Env"
