name: CI ReUse - Test Cases
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  NodeJS_Test:
    if: inputs.appType == 'nodejs'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test NodeJS"

  Maven_Test:
    if: inputs.appType == 'maven'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Maven"